### ISSUE TITLE
可以google，但是网速特别慢

### ISSUE THREAD

**Issue by tujinqiu** [sheng/ladder-ios#11]
装了app之后，开启VPN，可以google了，但是网速特别慢，开国内的其他网站同样很慢。能欧解决办法吗？
我的手机是iphone X, 11.3.1的系统

**Comment by tujinqiu** [comment]
重启手机之后好像就好了

**Comment by sheng** [comment]
@tujinqiu 

我粗略地解释一下吧，网速会受几个方面因素的影响，一个是 `PAC URL`，目前这个应用使用的是在线 `PAC`，意思也就是说每次连接应用配置成功的那个 `VPN` 时都会从指定的 `URL` 下载对应的 `PAC` 文档，随后的使用过程中也会有额外的下载行为（比如缓存过期后），所以那个 `URL` 指向的资源的响应速度会是影响网速的因素之一，默认的那个 `URL` 是我自己搭的，我自己用着速度还行。另一个因素，`Shadowsocks` 所在服务器的响应速度最为关键，这个不用多作解释。还有一个因素，也就是网络环境了。

我目前有个计划就是加一个持久化 `PAC` 文档的功能，就是说每次点“配置”的时候就自动去把 `PAC` 下载到本地，后续连接配置成功的 `VPN` 时就不需要再在线拉取了，不过这样有个坏处，也就是一旦远端的那个 `PAC` 更新了，得再点一次“配置”才行，所以打算把这个功能作为一个可选项。

**Comment by tujinqiu** [comment]
可以弄个定期更新的策略，比如几天更新一次

**Comment by sheng** [comment]
@tujinqiu 

我刚才做了一些调整，加入了定期更新 `PAC` 的策略（连接 `VPN` 后每小时自动尝试更新一次），你可以看一下 19898002715adaf05227b2ae60c0a59619c9dcf5。

**Comment by tujinqiu** [comment]
谢谢
