### ISSUE TITLE
默认pac url似乎被墙了

### ISSUE THREAD

**Issue by exgphe** [sheng/ladder-ios#13]
貌似aofei.org现在已经无法访问了，翻墙后可正常访问。

**Comment by sheng** [comment]
@exgphe 

我在 e479ce5406cc4298be8ffa297a1043353dc78a96 中把默认的 PAC URL 换成了 [https://git.io/gfwpac](https://git.io/gfwpac)，虽然这个 URL 不支持修改 `Proxies` 部分，但至少不会轻易被墙，而且只要把本地端口一直保持成默认的 `1081` 就没什么问题了。

**Comment by exgphe** [comment]
恢复正常了。真是太感谢了！
