### ISSUE TITLE
在真机上编译不成功，这是什么原因

### ISSUE THREAD

**Issue by Ziven-n** [sheng/ladder-ios#14]
![2018-06-04 18 09 45](https://user-images.githubusercontent.com/15608631/40911894-a99c8fd8-6822-11e8-918b-1c83817738d5.png)

**Comment by sheng** [comment]
在真机上调试程序需要[苹果开发者资格](https://developer.apple.com/programs)的签名。

苹果放出的这个 `Network Extensions` 目前仍然是需要经过开发者认证的账号才能使用，你可以找个朋友帮你安装到真机上。

Issue 和 #5 重复了。

**Comment by Ziven-n** [comment]
可是我用的就是开发者账号，公司的

**Comment by sheng** [comment]
@Ziven-n 

你是不是漏签了一个 Target 呀？

主的 Target “Ladder”需要签：

<img width="1038" alt="0" src="https://user-images.githubusercontent.com/5037285/40949494-e841b6ae-68a0-11e8-98b8-f16e4e176f7f.png">

然后 Target “PacketTunnel”也是需要签的：

<img width="1038" alt="1" src="https://user-images.githubusercontent.com/5037285/40949525-032584b4-68a1-11e8-91b1-323337d4caf3.png">

**Comment by Ziven-n** [comment]
啊，抱歉，确实漏掉了。可以了谢谢！
