### ISSUE TITLE
Disconnect On LockScreen

### ISSUE THREAD

**Issue by Taherismail17** [sheng/ladder-ios#21]
Hi, 
how can I make the vpn disconnect on the lock screen?
disconnectOnSleep = true doesn't work

**Comment by sheng** [comment]
The `disconnectOnSleep` is a flag indicating if the `VPN` should be disconnected when the device **sleeps**. I think your device does not immediately go to sleep after the screen is locked.

**Comment by Taherismail17** [comment]
Thanks
