### ISSUE TITLE
配置失败，这是什么原因

### ISSUE THREAD

**Issue by LaoDaYe** [sheng/ladder-ios#24]
[NEConfigurationManager loadC:1714  Failed to load configurations: Error Domain=NEConfigurationErrorDomain Code=10 "permission denied" UserInfo={NSLocalizedDescription=permission denied}
[NEVPNManager saveToPreferenc:337  Failed to save configuration: Error Domain=NEVPNErrorDomain Code=5 "permission denied" UserInfo={NSLocalizedDescription=permission denied}

**Comment by LaoDaYe** [comment]
[NEVPNManager saveToPreferenc:337  Failed to save configuration: Error Domain=NEVPNErrorDomain Code=5 "failed to make changes in SCPreferences: (null)" UserInfo={NSLocalizedDescription=failed to make changes in SCPreferences: (null)}

**Comment by sheng** [comment]
你没有赋权，你是不是点了拒绝？
