### ISSUE TITLE
配置后，提示配置成功，但是并不能访问google,youtube但是国内网站都能访问，这是什么原因？？？

### ISSUE THREAD

**Issue by 841766048** [sheng/ladder-ios#25]
系统是11.2的

**Comment by sheng** [comment]
和 Issue #12 重复了，是因为中国特供版手机导致的，没有得到网络数据的访问权限，你可以试一下我提到的那些解决方案。

**Comment by 841766048** [comment]
我在设置里设置了它可以访问数据啊？这样也不行吗？

**Comment by sheng** [comment]
那应该就没问题了啊，服务器地址和密码有输错吗？或者本地端口号又改成别的吗？用默认 PAC 的话，本地端口号只能是 1081。

**Comment by sheng** [comment]
有可能是，要不你试试改下服务器那边吧？
