### ISSUE TITLE
配置成功。不能用。感觉只是看的。

### ISSUE THREAD

**Issue by hhhaiai** [sheng/ladder-ios#27]
什么用没有 配置成功。不能用。
pac默认自己输入。不能用

**Comment by sheng** [comment]
？

**Comment by oliverhu** [comment]
@sheng  这种issue直接关了吧 一点信息都没有

**Comment by sheng** [comment]
@oliverhu 好的。

@hhhaiai 如果还有问题的话你可以重新打开 Issue 的。
