### ISSUE TITLE
不熟悉ss, 代码我编译运行起来了？然后怎么配置

### ISSUE THREAD

**Issue by captain-black** [sheng/ladder-ios#37]
我代码编译运行起来了。
请问本地地址和端口是怎么配置？
这跟我之前惯用的ss客户端有点区别，本地地址和端口一定要我填写才行..

**Comment by sheng** [comment]
保留默认值即可。

**Comment by captain-black** [comment]
是不是我编译的代码有问题...默认都是空的，textfield都显示placeholder的字符串而已。
我跟跟swift代码先。

**Comment by captain-black** [comment]
代码里面看到，ReadFromKeychain返回nil就不走下面的默认值设置代码了。大概是因为这样我没有默认值

**Comment by sheng** [comment]
不好意思，看来是我的失误了，当时移除 KechainAccess 依赖的时候没仔细看，我一会儿就修复，多谢提醒！
